language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run build
  - npm run coveralls
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
